import { useState, useEffect, useRef } from "react";

// ─── DATA ────────────────────────────────────────────────────────────────────

const CHAPTER_OVERVIEW = {
  title: "Chapter 4 — Bipolar Junction Transistors",
  sections: [
    { id: "4-1", title: "BJT Structure", summary: "Three doped regions (emitter, base, collector) form two pn junctions. Two types: npn and pnp. The base is thin and lightly doped; emitter is heavily doped." },
    { id: "4-2", title: "Basic BJT Operation", summary: "Forward-reverse bias: BE junction forward-biased, BC junction reverse-biased. IE = IC + IB. Most emitter electrons diffuse through the thin base into the collector." },
    { id: "4-3", title: "Characteristics & Parameters", summary: "βDC = IC/IB (current gain, also called hFE). αDC = IC/IE. VBE ≈ 0.7 V. Collector curves show saturation, active, and breakdown regions. DC load line connects cutoff (VCE = VCC) to saturation (IC(sat))." },
    { id: "4-4", title: "BJT as Amplifier", summary: "Voltage gain Av = RC/r'e. The transistor amplifies because a small ac base voltage produces a large ac collector voltage. DC uses uppercase subscripts; ac uses lowercase." },
    { id: "4-5", title: "BJT as Switch", summary: "Cutoff: IB = 0, VCE = VCC (open switch). Saturation: IC = (VCC − VCE(sat))/RC (closed switch). IB(min) = IC(sat)/βDC." },
    { id: "4-6", title: "Phototransistor", summary: "Base current generated by light (Iλ). IC = βDC·Iλ. Dark current ICEO in nA range. Used in optocouplers (LED + phototransistor) with CTR parameter." },
    { id: "4-7", title: "Categories & Packaging", summary: "Three broad categories: general-purpose/small-signal, power, and RF. Packages include DIP, SO, TO-92, TO-220, TO-3, etc." },
    { id: "4-8", title: "Troubleshooting", summary: "Test BJT as two diodes with DMM. Open junction reads OL. Common faults: open base resistor → cutoff; open collector → no IC; shorted junctions." },
  ],
};

const TF_QUESTIONS = [
  { id: "tf1", text: "A bipolar junction transistor has three terminals.", answer: true, section: "4-1", explanation: "The three terminals of a BJT are the base, emitter, and collector." },
  { id: "tf2", text: "The three regions of a BJT are base, emitter, and cathode.", answer: false, section: "4-1", explanation: "The three regions are base, emitter, and collector — not cathode. 'Cathode' is a diode terminal." },
  { id: "tf3", text: "For operation in the linear or active region, the base-emitter junction of a transistor is forward-biased.", answer: true, section: "4-2", explanation: "Active (linear) region requires BE junction forward-biased and BC junction reverse-biased (forward-reverse bias)." },
  { id: "tf4", text: "Two types of BJT are npn and pnp.", answer: true, section: "4-1", explanation: "npn has two n regions separated by a p base; pnp has two p regions separated by an n base." },
  { id: "tf5", text: "The base current and collector current are approximately equal.", answer: false, section: "4-2", explanation: "IB is much smaller than IC. The collector current is βDC times the base current (IC = βDC·IB)." },
  { id: "tf6", text: "The dc voltage gain of a transistor is designated βDC.", answer: false, section: "4-3", explanation: "βDC is the dc current gain (IC/IB), not voltage gain. Voltage gain is Av = RC/r'e." },
  { id: "tf7", text: "Cutoff and saturation are the two normal states of a linear transistor amplifier.", answer: false, section: "4-4", explanation: "A linear amplifier operates in the active (linear) region. Cutoff and saturation are the two states of a transistor switch." },
  { id: "tf8", text: "When a transistor is saturated, the collector current is maximum.", answer: true, section: "4-3", explanation: "In saturation, IC has reached its maximum value IC(sat) = (VCC − VCE(sat))/RC and cannot increase further." },
  { id: "tf9", text: "βDC and hFE are two different transistor parameters.", answer: false, section: "4-3", explanation: "They are the same parameter — both represent dc current gain (IC/IB). hFE is just the datasheet designation for βDC." },
  { id: "tf10", text: "Voltage gain of a transistor amplifier depends on the collector resistor and the internal ac resistance.", answer: true, section: "4-4", explanation: "Av = RC/r'e, so voltage gain depends on the collector resistance RC and the internal ac emitter resistance r'e." },
  { id: "tf11", text: "Amplification is the output voltage divided by the input current.", answer: false, section: "4-4", explanation: "Voltage amplification (gain) is output voltage divided by input voltage: Av = Vout/Vin. Dividing voltage by current gives impedance, not gain." },
  { id: "tf12", text: "A transistor in cutoff acts as an open switch.", answer: true, section: "4-5", explanation: "In cutoff, IB = 0, IC ≈ 0, and VCE = VCC — the transistor behaves like an open switch between collector and emitter." },
];

const CIRCUIT_QUESTIONS = [
  { id: "ca1", text: "If a transistor with a higher βDC is used in Figure 4–9, the collector current will", options: ["increase", "decrease", "not change"], answer: 0, section: "4-3", explanation: "IC = βDC·IB. With a higher βDC and the same IB (set by VBB, RB, and VBE), IC increases." },
  { id: "ca2", text: "If a transistor with a higher βDC is used in Figure 4–9, the emitter current will", options: ["increase", "decrease", "not change"], answer: 0, section: "4-3", explanation: "IE = IC + IB. Since IC increases with higher βDC while IB stays the same, IE also increases." },
  { id: "ca3", text: "If a transistor with a higher βDC is used in Figure 4–9, the base current will", options: ["increase", "decrease", "not change"], answer: 2, section: "4-3", explanation: "IB = (VBB − VBE)/RB. Base current depends only on VBB, VBE, and RB — not on βDC. It does not change." },
  { id: "ca4", text: "If VBB is reduced in Figure 4–16, the collector current will", options: ["increase", "decrease", "not change"], answer: 1, section: "4-3", explanation: "Reducing VBB decreases IB = (VBB − VBE)/RB, which in turn decreases IC = βDC·IB." },
  { id: "ca5", text: "If VCC in Figure 4–16 is increased, the base current will", options: ["increase", "decrease", "not change"], answer: 2, section: "4-3", explanation: "IB = (VBB − VBE)/RB. VCC does not appear in this equation, so changing VCC doesn't affect IB." },
  { id: "ca6", text: "If the amplitude of Vin in Figure 4–22 is decreased, the ac output voltage amplitude will", options: ["increase", "decrease", "not change"], answer: 1, section: "4-4", explanation: "Vout = Av·Vin. If Vin decreases, the output voltage decreases proportionally (gain stays the same)." },
  { id: "ca7", text: "If the transistor in Figure 4–24 is saturated and the base current is increased, the collector current will", options: ["increase", "decrease", "not change"], answer: 2, section: "4-5", explanation: "Once saturated, IC is at its maximum IC(sat). Increasing IB further cannot increase IC — it stays the same." },
  { id: "ca8", text: "If RC in Figure 4–24 is reduced in value, the value of IC(sat) will", options: ["increase", "decrease", "not change"], answer: 0, section: "4-5", explanation: "IC(sat) = (VCC − VCE(sat))/RC. A smaller RC means a larger IC(sat)." },
  { id: "ca9", text: "If the transistor in Figure 4–39 is open from collector to emitter, the voltage across RC will", options: ["increase", "decrease", "not change"], answer: 1, section: "4-8", explanation: "If open C-E, no current flows through RC, so the voltage across RC drops to 0 V (decreases from its normal value)." },
  { id: "ca10", text: "If the transistor in Figure 4–39 is open from collector to emitter, the collector voltage will", options: ["increase", "decrease", "not change"], answer: 0, section: "4-8", explanation: "With no IC, there's no drop across RC, so the collector voltage rises to VCC (increases)." },
  { id: "ca11", text: "If the base resistor in Figure 4–39 is open, the transistor collector voltage will", options: ["increase", "decrease", "not change"], answer: 0, section: "4-8", explanation: "An open base resistor means IB = 0, putting the transistor in cutoff. VCE = VCC, so collector voltage increases to VCC." },
  { id: "ca12", text: "If the emitter in Figure 4–39 becomes disconnected from ground, the collector voltage will", options: ["increase", "decrease", "not change"], answer: 0, section: "4-8", explanation: "No ground return means no current can flow. The transistor is effectively off, so VCE rises to VCC." },
];

const SELF_TEST_QUESTIONS = [
  { id: "st1", text: "The three terminals of a bipolar junction transistor are called", options: ["p, n, p", "n, p, n", "input, output, ground", "base, emitter, collector"], answer: 3, section: "4-1", explanation: "The three terminals are base (B), emitter (E), and collector (C)." },
  { id: "st2", text: "In a pnp transistor, the p regions are", options: ["base and emitter", "base and collector", "emitter and collector"], answer: 2, section: "4-1", explanation: "In a pnp transistor the two outer regions are p-type: the emitter and the collector. The base is n-type." },
  { id: "st3", text: "For operation as an amplifier, the base of an npn transistor must be", options: ["positive with respect to the emitter", "negative with respect to the emitter", "positive with respect to the collector", "0 V"], answer: 0, section: "4-2", explanation: "The BE junction must be forward-biased, so the base must be positive relative to the emitter (for npn)." },
  { id: "st4", text: "The emitter current is always", options: ["greater than the base current", "less than the collector current", "greater than the collector current", "answers (a) and (c)"], answer: 3, section: "4-2", explanation: "IE = IC + IB, so IE is greater than both IC and IB. Answers (a) and (c) are both true." },
  { id: "st5", text: "The βDC of a transistor is its", options: ["current gain", "voltage gain", "power gain", "internal resistance"], answer: 0, section: "4-3", explanation: "βDC = IC/IB, which is the dc current gain of the transistor." },
  { id: "st6", text: "If IC is 50 times larger than IB, then βDC is", options: ["0.02", "100", "50", "500"], answer: 2, section: "4-3", explanation: "βDC = IC/IB = 50IB/IB = 50." },
  { id: "st7", text: "The approximate voltage across the forward-biased base-emitter junction of a silicon BJT is", options: ["0 V", "0.7 V", "0.3 V", "VBB"], answer: 1, section: "4-3", explanation: "A forward-biased silicon pn junction has approximately 0.7 V across it." },
  { id: "st8", text: "The bias condition for a transistor to be used as a linear amplifier is called", options: ["forward-reverse", "forward-forward", "reverse-reverse", "collector bias"], answer: 0, section: "4-2", explanation: "Forward-reverse bias means BE junction forward-biased and BC junction reverse-biased — the active region for linear amplification." },
  { id: "st9", text: "If the output of a transistor amplifier is 5 V rms and the input is 100 mV rms, the voltage gain is", options: ["5", "500", "50", "100"], answer: 2, section: "4-4", explanation: "Av = Vout/Vin = 5 V / 0.1 V = 50." },
  { id: "st10", text: "When a lowercase r′ is used in relation to a transistor, it refers to", options: ["a low resistance", "a wire resistance", "an internal ac resistance", "a source resistance"], answer: 2, section: "4-4", explanation: "Lowercase r′ with a subscript (like r′e) designates an internal ac resistance of the transistor." },
  { id: "st11", text: "In a given transistor amplifier, RC = 2.2 kΩ and r′e = 20 Ω, the voltage gain is", options: ["2.2", "110", "20", "44"], answer: 1, section: "4-4", explanation: "Av = RC/r′e = 2200/20 = 110." },
  { id: "st12", text: "When operated in cutoff and saturation, the transistor acts like a", options: ["linear amplifier", "switch", "variable capacitor", "variable resistor"], answer: 1, section: "4-5", explanation: "Switching between cutoff (open) and saturation (closed) makes the transistor function as an electronic switch." },
  { id: "st13", text: "In cutoff, VCE is", options: ["0 V", "minimum", "maximum", "equal to VCC", "answers (a) and (b)", "answers (c) and (d)"], answer: 5, section: "4-5", explanation: "In cutoff IC ≈ 0, so there's no drop across RC. VCE = VCC, which is its maximum value. Both (c) and (d) are correct." },
  { id: "st14", text: "In saturation, VCE is", options: ["0.7 V", "equal to VCC", "minimum", "maximum"], answer: 2, section: "4-5", explanation: "In saturation VCE drops to VCE(sat), typically a few tenths of a volt — its minimum value." },
  { id: "st15", text: "To saturate a BJT,", options: ["IB = IC(sat)", "IB > IC(sat)/βDC", "VCC must be at least 10 V", "the emitter must be grounded"], answer: 1, section: "4-5", explanation: "Saturation requires enough base current so that IC reaches IC(sat). The minimum IB needed is IC(sat)/βDC, so IB must exceed this." },
  { id: "st16", text: "Once in saturation, a further increase in base current will", options: ["cause the collector current to increase", "not affect the collector current", "cause the collector current to decrease", "turn the transistor off"], answer: 1, section: "4-5", explanation: "Once saturated, IC is at maximum. More IB cannot push IC higher — the relationship IC = βDC·IB no longer holds." },
  { id: "st17", text: "In a phototransistor, base current is", options: ["set by a bias voltage", "directly proportional to light intensity", "inversely proportional to light intensity", "not a factor"], answer: 1, section: "4-6", explanation: "In a phototransistor, incident light generates the base current (Iλ), which is directly proportional to light intensity." },
  { id: "st18", text: "The relationship between the collector current and a light-generated base current is", options: ["IC = βDC·Iλ", "IC = αDC·Iλ", "IC = λ·Iλ", "IC = β²DC·Iλ"], answer: 0, section: "4-6", explanation: "Just like a regular BJT, IC = βDC times the base current. For a phototransistor, that base current is the light-generated Iλ." },
  { id: "st19", text: "An optocoupler usually consists of", options: ["two LEDs", "an LED and a photodiode", "an LED and a phototransistor", "both (b) and (c)"], answer: 3, section: "4-6", explanation: "Optocouplers come in two basic types: LED-to-photodiode and LED-to-phototransistor. Both (b) and (c) are valid." },
  { id: "st20", text: "In a transistor amplifier, if the base-emitter junction is open, the collector voltage is", options: ["VCC", "0 V", "floating", "0.2 V"], answer: 0, section: "4-8", explanation: "An open BE junction means IB = 0 → IC = 0 → no voltage drop across RC → collector sits at VCC." },
  { id: "st21", text: "A DMM measuring an open transistor junction shows", options: ["0 V", "0.7 V", "OL", "VCC"], answer: 2, section: "4-8", explanation: "An open junction has infinite resistance, so the DMM reads OL (over-limit/open-loop), indicating no continuity." },
];

const ALL_QUESTIONS = [
  ...TF_QUESTIONS.map(q => ({ ...q, category: "True/False" })),
  ...CIRCUIT_QUESTIONS.map(q => ({ ...q, category: "Circuit Action" })),
  ...SELF_TEST_QUESTIONS.map(q => ({ ...q, category: "Self-Test" })),
];

// ─── STYLES ──────────────────────────────────────────────────────────────────

const theme = {
  bg: "#0f1117",
  surface: "#1a1d27",
  surfaceHover: "#222633",
  border: "#2a2e3d",
  borderLight: "#353a4d",
  text: "#e2e4ea",
  textMuted: "#8b90a0",
  textDim: "#5c6175",
  accent: "#6c9fff",
  accentDim: "#3d6abf",
  correct: "#3dd68c",
  correctBg: "rgba(61,214,140,0.08)",
  correctBorder: "rgba(61,214,140,0.25)",
  wrong: "#ff6b7a",
  wrongBg: "rgba(255,107,122,0.08)",
  wrongBorder: "rgba(255,107,122,0.25)",
  warning: "#f0b955",
  warningBg: "rgba(240,185,85,0.08)",
  purple: "#a78bfa",
  purpleBg: "rgba(167,139,250,0.08)",
};

// ─── COMPONENTS ──────────────────────────────────────────────────────────────

function Badge({ children, color = theme.accent, bg = "rgba(108,159,255,0.1)" }) {
  return (
    <span style={{
      display: "inline-block",
      padding: "2px 10px",
      borderRadius: "999px",
      fontSize: "11px",
      fontWeight: 600,
      letterSpacing: "0.3px",
      color,
      background: bg,
      border: `1px solid ${color}33`,
      whiteSpace: "nowrap",
    }}>{children}</span>
  );
}

function SectionBadge({ section }) {
  return <Badge color={theme.purple} bg={theme.purpleBg}>§{section}</Badge>;
}

function CategoryBadge({ category }) {
  const colors = {
    "True/False": { c: theme.accent, b: "rgba(108,159,255,0.1)" },
    "Circuit Action": { c: theme.warning, b: theme.warningBg },
    "Self-Test": { c: theme.purple, b: theme.purpleBg },
  };
  const { c, b } = colors[category] || colors["Self-Test"];
  return <Badge color={c} bg={b}>{category}</Badge>;
}

// ─── CHAPTER OVERVIEW ────────────────────────────────────────────────────────

function ChapterOverview({ expanded, onToggle }) {
  return (
    <div style={{
      background: theme.surface,
      border: `1px solid ${theme.border}`,
      borderRadius: "12px",
      overflow: "hidden",
      marginBottom: "24px",
    }}>
      <button onClick={onToggle} style={{
        width: "100%",
        padding: "16px 20px",
        background: "none",
        border: "none",
        color: theme.text,
        cursor: "pointer",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        fontFamily: "inherit",
        fontSize: "15px",
        fontWeight: 600,
      }}>
        <span style={{ display: "flex", alignItems: "center", gap: "10px" }}>
          <span style={{ fontSize: "18px" }}>📖</span>
          {CHAPTER_OVERVIEW.title}
        </span>
        <span style={{
          transform: expanded ? "rotate(180deg)" : "rotate(0)",
          transition: "transform 0.25s ease",
          fontSize: "12px",
          color: theme.textMuted,
        }}>▼</span>
      </button>
      {expanded && (
        <div style={{ padding: "0 20px 20px", display: "flex", flexDirection: "column", gap: "12px" }}>
          <div style={{ height: "1px", background: theme.border, marginBottom: "4px" }} />
          {CHAPTER_OVERVIEW.sections.map(s => (
            <div key={s.id} style={{
              padding: "12px 16px",
              background: theme.bg,
              borderRadius: "8px",
              border: `1px solid ${theme.border}`,
            }}>
              <div style={{ display: "flex", alignItems: "center", gap: "8px", marginBottom: "6px" }}>
                <span style={{ color: theme.accent, fontWeight: 700, fontSize: "13px", fontFamily: "'JetBrains Mono', monospace" }}>{s.id}</span>
                <span style={{ color: theme.text, fontWeight: 600, fontSize: "14px" }}>{s.title}</span>
              </div>
              <p style={{ color: theme.textMuted, fontSize: "13px", lineHeight: 1.55, margin: 0 }}>{s.summary}</p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// ─── QUESTION VISUALIZER ─────────────────────────────────────────────────────

function QuestionCard({ q, index }) {
  const [open, setOpen] = useState(false);
  const isTF = q.category === "True/False";
  const isCircuit = q.category === "Circuit Action";

  const answerText = isTF
    ? (q.answer ? "True" : "False")
    : isCircuit
      ? q.options[q.answer]
      : q.options[q.answer];

  return (
    <div style={{
      background: theme.surface,
      border: `1px solid ${theme.border}`,
      borderRadius: "10px",
      overflow: "hidden",
      transition: "border-color 0.2s",
    }}>
      <button onClick={() => setOpen(!open)} style={{
        width: "100%",
        padding: "14px 16px",
        background: "none",
        border: "none",
        color: theme.text,
        cursor: "pointer",
        display: "flex",
        alignItems: "flex-start",
        gap: "12px",
        textAlign: "left",
        fontFamily: "inherit",
        fontSize: "13.5px",
        lineHeight: 1.5,
      }}>
        <span style={{
          flexShrink: 0,
          width: "26px",
          height: "26px",
          borderRadius: "6px",
          background: theme.bg,
          border: `1px solid ${theme.border}`,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          fontSize: "12px",
          fontWeight: 700,
          color: theme.textMuted,
          fontFamily: "'JetBrains Mono', monospace",
        }}>{index + 1}</span>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ marginBottom: "8px" }}>{q.text}</div>
          <div style={{ display: "flex", gap: "6px", flexWrap: "wrap" }}>
            <CategoryBadge category={q.category} />
            <SectionBadge section={q.section} />
          </div>
        </div>
        <span style={{
          flexShrink: 0,
          fontSize: "11px",
          color: theme.textDim,
          transform: open ? "rotate(180deg)" : "rotate(0)",
          transition: "transform 0.2s",
          marginTop: "4px",
        }}>▼</span>
      </button>
      {open && (
        <div style={{ padding: "0 16px 14px 54px" }}>
          <div style={{ height: "1px", background: theme.border, marginBottom: "12px" }} />
          <div style={{
            padding: "10px 14px",
            background: theme.correctBg,
            border: `1px solid ${theme.correctBorder}`,
            borderRadius: "8px",
            marginBottom: "8px",
          }}>
            <span style={{ color: theme.correct, fontWeight: 700, fontSize: "12px", textTransform: "uppercase", letterSpacing: "0.5px" }}>Answer: </span>
            <span style={{ color: theme.correct, fontSize: "13.5px", fontWeight: 600 }}>{answerText}</span>
          </div>
          <p style={{ color: theme.textMuted, fontSize: "13px", lineHeight: 1.55, margin: 0 }}>{q.explanation}</p>
        </div>
      )}
    </div>
  );
}

function Visualizer() {
  const [overviewOpen, setOverviewOpen] = useState(false);
  const [filter, setFilter] = useState("all");

  const filtered = filter === "all"
    ? ALL_QUESTIONS
    : ALL_QUESTIONS.filter(q => q.category === filter);

  const categories = ["all", "True/False", "Circuit Action", "Self-Test"];

  return (
    <div>
      <ChapterOverview expanded={overviewOpen} onToggle={() => setOverviewOpen(!overviewOpen)} />

      <div style={{ display: "flex", gap: "8px", marginBottom: "20px", flexWrap: "wrap" }}>
        {categories.map(cat => (
          <button key={cat} onClick={() => setFilter(cat)} style={{
            padding: "7px 16px",
            borderRadius: "8px",
            border: `1px solid ${filter === cat ? theme.accent : theme.border}`,
            background: filter === cat ? "rgba(108,159,255,0.12)" : theme.surface,
            color: filter === cat ? theme.accent : theme.textMuted,
            cursor: "pointer",
            fontSize: "13px",
            fontWeight: 600,
            fontFamily: "inherit",
            transition: "all 0.15s",
          }}>{cat === "all" ? `All (${ALL_QUESTIONS.length})` : `${cat} (${ALL_QUESTIONS.filter(q => q.category === cat).length})`}</button>
        ))}
      </div>

      <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
        {filtered.map((q, i) => <QuestionCard key={q.id} q={q} index={i} />)}
      </div>
    </div>
  );
}

// ─── TEST MODE ───────────────────────────────────────────────────────────────

function TestCategorySelect({ onSelect }) {
  const cats = [
    { key: "True/False", icon: "✓✗", count: TF_QUESTIONS.length, desc: "True or False statements" },
    { key: "Circuit Action", icon: "⚡", count: CIRCUIT_QUESTIONS.length, desc: "Predict circuit behavior changes" },
    { key: "Self-Test", icon: "📝", count: SELF_TEST_QUESTIONS.length, desc: "Multiple choice from all sections" },
    { key: "all", icon: "🎯", count: ALL_QUESTIONS.length, desc: "Everything combined & shuffled" },
  ];

  return (
    <div style={{ maxWidth: "480px", margin: "0 auto", paddingTop: "40px" }}>
      <h2 style={{ color: theme.text, fontSize: "22px", fontWeight: 700, marginBottom: "6px", textAlign: "center" }}>Test Mode</h2>
      <p style={{ color: theme.textMuted, fontSize: "14px", textAlign: "center", marginBottom: "32px" }}>Choose which questions to practice</p>
      <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
        {cats.map(c => (
          <button key={c.key} onClick={() => onSelect(c.key)} style={{
            padding: "18px 20px",
            background: theme.surface,
            border: `1px solid ${theme.border}`,
            borderRadius: "12px",
            cursor: "pointer",
            display: "flex",
            alignItems: "center",
            gap: "16px",
            color: theme.text,
            fontFamily: "inherit",
            textAlign: "left",
            transition: "border-color 0.15s, background 0.15s",
          }}
          onMouseEnter={e => { e.currentTarget.style.borderColor = theme.accentDim; e.currentTarget.style.background = theme.surfaceHover; }}
          onMouseLeave={e => { e.currentTarget.style.borderColor = theme.border; e.currentTarget.style.background = theme.surface; }}
          >
            <span style={{ fontSize: "24px", width: "40px", textAlign: "center" }}>{c.icon}</span>
            <div style={{ flex: 1 }}>
              <div style={{ fontWeight: 700, fontSize: "15px", marginBottom: "2px" }}>{c.key === "all" ? "All Questions" : c.key}</div>
              <div style={{ fontSize: "12.5px", color: theme.textMuted }}>{c.desc}</div>
            </div>
            <span style={{
              padding: "4px 12px",
              borderRadius: "999px",
              background: theme.bg,
              border: `1px solid ${theme.border}`,
              fontSize: "13px",
              fontWeight: 700,
              color: theme.textMuted,
              fontFamily: "'JetBrains Mono', monospace",
            }}>{c.count}</span>
          </button>
        ))}
      </div>
    </div>
  );
}

function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function TestQuestion({ q, qIndex, total, onAnswer }) {
  const [selected, setSelected] = useState(null);
  const [confirmed, setConfirmed] = useState(false);
  const isTF = q.category === "True/False";

  const options = isTF
    ? [{ label: "True", value: true }, { label: "False", value: false }]
    : q.options.map((o, i) => ({ label: o, value: i }));

  const correctValue = isTF ? q.answer : q.answer;

  const handleConfirm = () => {
    setConfirmed(true);
    setTimeout(() => {
      onAnswer(selected === correctValue);
    }, 1200);
  };

  const isCorrect = selected === correctValue;

  return (
    <div style={{ maxWidth: "600px", margin: "0 auto" }}>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "24px" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
          <CategoryBadge category={q.category} />
          <SectionBadge section={q.section} />
        </div>
        <span style={{ color: theme.textMuted, fontSize: "13px", fontWeight: 600, fontFamily: "'JetBrains Mono', monospace" }}>
          {qIndex + 1}/{total}
        </span>
      </div>

      {/* progress bar */}
      <div style={{ height: "3px", background: theme.border, borderRadius: "99px", marginBottom: "28px", overflow: "hidden" }}>
        <div style={{
          height: "100%",
          width: `${((qIndex + 1) / total) * 100}%`,
          background: theme.accent,
          borderRadius: "99px",
          transition: "width 0.4s ease",
        }} />
      </div>

      <h3 style={{ color: theme.text, fontSize: "17px", fontWeight: 600, lineHeight: 1.55, marginBottom: "24px" }}>{q.text}</h3>

      <div style={{ display: "flex", flexDirection: "column", gap: "8px", marginBottom: "24px" }}>
        {options.map((opt, i) => {
          const isThis = selected === opt.value;
          const showCorrect = confirmed && opt.value === correctValue;
          const showWrong = confirmed && isThis && !isCorrect;

          let borderColor = theme.border;
          let bg = theme.surface;
          let textColor = theme.text;
          if (!confirmed && isThis) { borderColor = theme.accent; bg = "rgba(108,159,255,0.08)"; }
          if (showCorrect) { borderColor = theme.correctBorder; bg = theme.correctBg; textColor = theme.correct; }
          if (showWrong) { borderColor = theme.wrongBorder; bg = theme.wrongBg; textColor = theme.wrong; }

          return (
            <button key={i} onClick={() => !confirmed && setSelected(opt.value)} disabled={confirmed} style={{
              padding: "14px 16px",
              background: bg,
              border: `1.5px solid ${borderColor}`,
              borderRadius: "10px",
              color: textColor,
              cursor: confirmed ? "default" : "pointer",
              fontFamily: "inherit",
              fontSize: "14px",
              textAlign: "left",
              display: "flex",
              alignItems: "center",
              gap: "12px",
              transition: "all 0.15s",
              opacity: confirmed && !showCorrect && !showWrong ? 0.4 : 1,
            }}>
              <span style={{
                width: "24px",
                height: "24px",
                borderRadius: "6px",
                border: `1.5px solid ${isThis && !confirmed ? theme.accent : showCorrect ? theme.correct : showWrong ? theme.wrong : theme.borderLight}`,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                fontSize: "11px",
                fontWeight: 700,
                color: theme.textDim,
                background: showCorrect ? theme.correctBg : showWrong ? theme.wrongBg : "transparent",
                fontFamily: "'JetBrains Mono', monospace",
                flexShrink: 0,
              }}>
                {showCorrect ? "✓" : showWrong ? "✗" : String.fromCharCode(65 + i)}
              </span>
              {opt.label}
            </button>
          );
        })}
      </div>

      {!confirmed && (
        <button onClick={handleConfirm} disabled={selected === null} style={{
          width: "100%",
          padding: "14px",
          borderRadius: "10px",
          border: "none",
          background: selected !== null ? theme.accent : theme.border,
          color: selected !== null ? "#0f1117" : theme.textDim,
          cursor: selected !== null ? "pointer" : "not-allowed",
          fontSize: "14px",
          fontWeight: 700,
          fontFamily: "inherit",
          transition: "all 0.15s",
        }}>Confirm</button>
      )}

      {confirmed && (
        <div style={{
          padding: "12px 16px",
          background: isCorrect ? theme.correctBg : theme.wrongBg,
          border: `1px solid ${isCorrect ? theme.correctBorder : theme.wrongBorder}`,
          borderRadius: "10px",
          color: isCorrect ? theme.correct : theme.wrong,
          fontSize: "13.5px",
          fontWeight: 600,
          textAlign: "center",
        }}>{isCorrect ? "Correct!" : "Incorrect"}</div>
      )}
    </div>
  );
}

function TestResults({ questions, answers, onRestart, onMenu }) {
  const wrong = questions.map((q, i) => ({ ...q, userCorrect: answers[i] })).filter(r => !r.userCorrect);
  const score = answers.filter(Boolean).length;
  const total = answers.length;
  const pct = Math.round((score / total) * 100);

  const sectionErrors = {};
  wrong.forEach(q => {
    if (!sectionErrors[q.section]) sectionErrors[q.section] = [];
    sectionErrors[q.section].push(q);
  });

  return (
    <div style={{ maxWidth: "600px", margin: "0 auto" }}>
      <div style={{ textAlign: "center", marginBottom: "32px", paddingTop: "20px" }}>
        <div style={{
          width: "100px",
          height: "100px",
          borderRadius: "50%",
          border: `4px solid ${pct >= 90 ? theme.correct : pct >= 70 ? theme.warning : theme.wrong}`,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          margin: "0 auto 16px",
          fontSize: "28px",
          fontWeight: 800,
          color: pct >= 90 ? theme.correct : pct >= 70 ? theme.warning : theme.wrong,
          fontFamily: "'JetBrains Mono', monospace",
        }}>{pct}%</div>
        <h2 style={{ color: theme.text, fontSize: "20px", fontWeight: 700, marginBottom: "4px" }}>
          {pct === 100 ? "Perfect Score! 🎉" : pct >= 90 ? "Great Job!" : pct >= 70 ? "Good Effort" : "Keep Practicing"}
        </h2>
        <p style={{ color: theme.textMuted, fontSize: "14px" }}>{score} of {total} correct</p>
      </div>

      {wrong.length > 0 && (
        <div style={{ marginBottom: "28px" }}>
          <h3 style={{ color: theme.wrong, fontSize: "14px", fontWeight: 700, marginBottom: "14px", textTransform: "uppercase", letterSpacing: "0.5px" }}>
            Questions to Review ({wrong.length})
          </h3>

          {Object.entries(sectionErrors).sort(([a],[b]) => a.localeCompare(b)).map(([sec, qs]) => (
            <div key={sec} style={{ marginBottom: "16px" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "8px", marginBottom: "8px" }}>
                <SectionBadge section={sec} />
                <span style={{ color: theme.textMuted, fontSize: "12px" }}>
                  {CHAPTER_OVERVIEW.sections.find(s => s.id === sec)?.title}
                </span>
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
                {qs.map(q => (
                  <div key={q.id} style={{
                    padding: "12px 14px",
                    background: theme.wrongBg,
                    border: `1px solid ${theme.wrongBorder}`,
                    borderRadius: "8px",
                  }}>
                    <p style={{ color: theme.text, fontSize: "13px", margin: "0 0 8px", lineHeight: 1.45 }}>{q.text}</p>
                    <p style={{ color: theme.correct, fontSize: "12.5px", margin: 0, fontWeight: 600 }}>
                      ✓ {q.category === "True/False" ? (q.answer ? "True" : "False") : q.options[q.answer]}
                    </p>
                    <p style={{ color: theme.textMuted, fontSize: "12px", margin: "4px 0 0", lineHeight: 1.45 }}>{q.explanation}</p>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      )}

      <div style={{ display: "flex", gap: "10px" }}>
        <button onClick={onRestart} style={{
          flex: 1,
          padding: "14px",
          borderRadius: "10px",
          border: `1.5px solid ${theme.accent}`,
          background: "transparent",
          color: theme.accent,
          cursor: "pointer",
          fontSize: "14px",
          fontWeight: 700,
          fontFamily: "inherit",
        }}>Restart</button>
        <button onClick={onMenu} style={{
          flex: 1,
          padding: "14px",
          borderRadius: "10px",
          border: "none",
          background: theme.accent,
          color: "#0f1117",
          cursor: "pointer",
          fontSize: "14px",
          fontWeight: 700,
          fontFamily: "inherit",
        }}>Menu</button>
      </div>
    </div>
  );
}

function TestMode({ onBack }) {
  const [category, setCategory] = useState(null);
  const [questions, setQuestions] = useState([]);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [answers, setAnswers] = useState([]);
  const [phase, setPhase] = useState("select"); // select, testing, results

  const startTest = (cat) => {
    setCategory(cat);
    let pool;
    if (cat === "all") pool = ALL_QUESTIONS;
    else pool = ALL_QUESTIONS.filter(q => q.category === cat);
    setQuestions(shuffle(pool));
    setAnswers([]);
    setCurrentIndex(0);
    setPhase("testing");
  };

  const handleAnswer = (correct) => {
    const newAnswers = [...answers, correct];
    setAnswers(newAnswers);
    if (currentIndex + 1 >= questions.length) {
      setTimeout(() => setPhase("results"), 200);
    } else {
      setTimeout(() => setCurrentIndex(currentIndex + 1), 200);
    }
  };

  if (phase === "select") return <TestCategorySelect onSelect={startTest} />;
  if (phase === "results") return (
    <TestResults
      questions={questions}
      answers={answers}
      onRestart={() => startTest(category)}
      onMenu={() => setPhase("select")}
    />
  );

  return (
    <TestQuestion
      key={currentIndex}
      q={questions[currentIndex]}
      qIndex={currentIndex}
      total={questions.length}
      onAnswer={handleAnswer}
    />
  );
}

// ─── MAIN APP ────────────────────────────────────────────────────────────────

export default function App() {
  const [tab, setTab] = useState("visualizer");

  return (
    <div style={{
      minHeight: "100vh",
      background: theme.bg,
      color: theme.text,
      fontFamily: "'Inter', 'SF Pro Display', -apple-system, sans-serif",
    }}>
      <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500;600;700&display=swap" rel="stylesheet" />

      {/* Header */}
      <div style={{
        position: "sticky",
        top: 0,
        zIndex: 100,
        background: "rgba(15,17,23,0.85)",
        backdropFilter: "blur(12px)",
        borderBottom: `1px solid ${theme.border}`,
      }}>
        <div style={{ maxWidth: "720px", margin: "0 auto", padding: "12px 20px", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
            <span style={{ fontSize: "18px" }}>⚡</span>
            <span style={{ fontWeight: 800, fontSize: "15px", letterSpacing: "-0.3px" }}>BJT Mastery</span>
            <span style={{ color: theme.textDim, fontSize: "12px", fontWeight: 500 }}>Ch. 4</span>
          </div>
          <div style={{
            display: "flex",
            gap: "2px",
            background: theme.surface,
            borderRadius: "8px",
            padding: "3px",
            border: `1px solid ${theme.border}`,
          }}>
            {[
              { key: "visualizer", label: "📚 Study" },
              { key: "test", label: "🧪 Test" },
            ].map(t => (
              <button key={t.key} onClick={() => setTab(t.key)} style={{
                padding: "6px 14px",
                borderRadius: "6px",
                border: "none",
                background: tab === t.key ? theme.accent : "transparent",
                color: tab === t.key ? "#0f1117" : theme.textMuted,
                cursor: "pointer",
                fontSize: "12.5px",
                fontWeight: 700,
                fontFamily: "inherit",
                transition: "all 0.15s",
              }}>{t.label}</button>
            ))}
          </div>
        </div>
      </div>

      {/* Content */}
      <div style={{ maxWidth: "720px", margin: "0 auto", padding: "24px 20px 60px" }}>
        {tab === "visualizer" && <Visualizer />}
        {tab === "test" && <TestMode />}
      </div>
    </div>
  );
}
